modLoader="javafml"
loaderVersion="[28,)"

issueTrackerURL="https://github.com/Harleyoc1/ChunkAnimator/issues"

license="MIT"

[[mods]]

displayName="Chunk Animator"
modId="chunkanimator"
version="${file.jarVersion}"

authors="Lumien"
credits="Harley O'Connor for this port"

description='''
A small client side mod that animates the appeareance of chunks so that they don't just instantly appear.
'''

displayURL="https://www.curseforge.com/minecraft/mc-mods/chunk-animator"
updateJSONURL="https://github.com/Harleyoc1/ChunkAnimator/blob/1.14.4/version_info.json?raw=true"

[[dependencies.chunkanimator]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chunkanimator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4,)"
    ordering="NONE"
    side="BOTH"